### PR TITLE
R20.2 new icons

### PR DESCRIPTION
**Pull request by dougkenik**
Replaced the icons with the new ones for login, top left main screen, and about

### CODE REVIEW

**Review by bradymadams — APPROVED** [review]
Looks good to me. Are there unused images that we can remove from the repo?

**Comment by dougkenik** [comment]
> Looks good to me. Are there unused images that we can remove from the repo?

Removed the unused images

**Review by bradymadams — APPROVED** [review]

**Review by colman-hartinger — APPROVED** [review]

**Review by jake-kirkland-teton — COMMENTED** [review]
Everything looks good on this one save one question I have:

Do we want to have the logo be behind popups and things, z-level wise? If you make your window really wide, but really short, you get overlap:

image

**Comment by dougkenik** [comment]
> Everything looks good on this one save one question I have:
> 
> Do we want to have the logo be behind popups and things, z-level wise? If you make your window really wide, but really short, you get overlap:
> 
> image

I don't think this is a huge deal, and I also don't know how easy of a fix this is

**Review by jake-kirkland-teton — APPROVED** [review]

**Pull request merged**
