### PR TITLE
R21.0 498

### PR DESCRIPTION
**Pull request by dougkenik**
Fix for #498 

I fixed the root of the problem for this fatal crash, and added some functionality based on current back-end status:

1. We don't track "Generate Support" anymore. So, turning it on and off should not trigger a tracked change in SmartSlice unless the support Extruders are set to 2
2. We will always now check the support extruders, even if Generate Support is turned off - this is an issue we found recently, and had to put a message in the back-end to provide more information. We can revert this back once the back-end allows support to be something other than Extruder 1
3. I cleaned up the tracking and restoring for the extruder properties

### CODE REVIEW

**Review by bradymadams — APPROVED** [review]
I don't think I fully appreciate the logic necessary here, but nothing stands out as problematic to me.

**Review by colman-hartinger — APPROVED** [review]
looks good to me

**Review by bradymadams — APPROVED** [review]
Works nicely. I tried to break it, but wasn't able to.

**Comment by bradymadams** [comment]
Build for @rickdalgarno 
https://teton-cdn.s3-us-west-2.amazonaws.com/smartslice-cura-plugin/dist/SmartSlicePlugin-r21.0-498.12.curapackage

**Comment by dougkenik** [comment]
@rickdalgarno - new build with the fix we discussed
[SmartSlicePlugin-r21.0-498.14.zip](https://github.com/tetonsim/is-cura-ui/files/6319664/SmartSlicePlugin-r21.0-498.14.zip)

**Comment by dougkenik** [comment]
@rickdalgarno  new build after our latest conversation
[SmartSlicePlugin-r21.0-498.15.zip](https://github.com/tetonsim/is-cura-ui/files/6321053/SmartSlicePlugin-r21.0-498.15.zip)

**Comment by rickdalgarno** [comment]
> @rickdalgarno new build after our latest conversation
> [SmartSlicePlugin-r21.0-498.15.zip](https://github.com/tetonsim/is-cura-ui/files/6321053/SmartSlicePlugin-r21.0-498.15.zip)

Using this build, Cura crashes right after I open the .3mf that is in issue #498.

image

**Comment by dougkenik** [comment]
@rickdalgarno - that was a bug introduced by a different PR. Good catch. Everything should be fixed now
[SmartSlicePlugin-r21.0-498.16.zip](https://github.com/tetonsim/is-cura-ui/files/6321181/SmartSlicePlugin-r21.0-498.16.zip)

**Review by rickdalgarno — APPROVED** [review]
Tested this and confirm that (a) we no longer track the "Support Generation" parameter, (b) issue #498 is resolved, and (c) the warning messages issued make sense when changing between extruder 1 and 2 and when changing the adhesion and support extruders.

**Pull request merged**
