### PR TITLE
R20.2 405

### PR DESCRIPTION
**Pull request by dougkenik**
Brady figured out how to fix the formatting, so I implemented it.

I also fixed the material warning popup. It was displaying at odd times, so I changed the behavior. It will only show the first time a user selects a material which has not been tested, but uses a generic equivalent

### CODE REVIEW

**Comment by bradymadams** [comment]
[Build](https://teton-cdn.s3-us-west-2.amazonaws.com/smartslice-cura-plugin/dist/SmartSlicePlugin-r20.2-405.48.curapackage)

**Review by bradymadams — APPROVED** [review]

**Review by rickdalgarno — CHANGES_REQUESTED** [review]
Tested and confirmed fix for #405.

However, there is no material popup when I select an untested material. I cycled through several untested materials, and never saw a "this material has not been tested.. generic equivalent" popup.

**Review by rickdalgarno — APPROVED** [review]
Choosing a variety of tested, supported and not tested, and unsupported materials results in expected behavior.

**Review by jake-kirkland-teton — APPROVED** [review]
I'm both glad and pissed at how easy this change was. Nice job @bradymadams

**Pull request merged**
