### PR TITLE
Partial Fix for #321

### PR DESCRIPTION
**Pull request by jake-kirkland-teton**

### CODE REVIEW

**Comment by bradymadams** [comment]
Now I remember this - I don't think we can use `set_from_cache=False` because, if I recall correctly, this triggers property change signals to emit. We then get those emissions and think the property was changed by the user. That was a long time ago though, so maybe our property tracking doesn't suffer from that problem anymore.

**Comment by dougkenik** [comment]
Yeah, you're right. The only way I see around this is to also track the `state ` variable for all of the extruder settings, and then we could maybe use that to determine if we cache the properties or not

**Comment by dougkenik** [comment]
actually - @bradymadams, the way Jake implemented it works really well. The only thing we can't do is this:

1. Optimization, or validating
2.  Change the print profile
3. Select "Discard" when it asks if you want to Keep or Discard the changes
4. Select "Cancel" from our prompt
5. Everything reverts fine, but the Star icon next to the print profile doesn't come back (it should)

**Review by colman-hartinger — COMMENTED** [review]
All the code looks good to me. Will run everything tomorrow morning when I'm back in the office

**Review by colman-hartinger — APPROVED** [review]
Just ran some optimization jobs and the changed setting is now visible. Didn't seem to effect anything else

**Review by bradymadams — APPROVED** [review]
@dougkenik sorry, forgot about this one. Do you want to change it to merge to r20.2?

**Comment by dougkenik** [comment]
> @dougkenik sorry, forgot about this one. Do you want to change it to merge to r20.2?

I'm open to putting it into the r20.1 branch that we just made the fix for the Cura crash or put it into r20.2. What are your thoughts?

**Comment by bradymadams** [comment]
> > @dougkenik sorry, forgot about this one. Do you want to change it to merge to r20.2?
> 
> I'm open to putting it into the r20.1 branch that we just made the fix for the Cura crash or put it into r20.2. What are your thoughts?

Unless, there's a reason we need to create another r20.1 release it should go into r20.2.

**Comment by jake-kirkland-teton** [comment]
Want me to merge it into 20.2 then?

**Comment by dougkenik** [comment]
Yeah

**Comment by jake-kirkland-teton** [comment]
Should be clear to merge.

**Review by bradymadams — CHANGES_REQUESTED** [review]
Empty lines got added to the JSONs. Let's remove those and then I can merge it.

**Comment by jake-kirkland-teton** [comment]
> 
> 
> Empty lines got added to the JSONs. Let's remove those and then I can merge it.

So they did. Fixed.

**Review by bradymadams — APPROVED** [review]

**Pull request merged**
