### PR TITLE
R21.0 fonts

### LINKED ISSUE #191: Ensure colors follow Cura Themes
We need to ensure all of our colors are matching Cura themes, so when a user selects a different theme, the colors follow suit. We need to comb our QML and python code to ensure the colors follow the theme (below is an example)

### PR DESCRIPTION
**Pull request by dougkenik**
Fixes #191 and also aligns themes to Blade by BigRep

### CODE REVIEW

**Comment by colman-hartinger** [comment]
@dougkenik I'm not sure why it's not showing up in the diffs but can you merge the latest changes from r20.1 into this branch. That should clear up the conflicts. All the code looks good to me

**Comment by bradymadams** [comment]
Code looks good to me too. Conflicts just need to be resolved. One question though - since this is for Blade do we want to align these updates with our recent release (20.2), rather than putting them in the next release (21.0)?

**Comment by dougkenik** [comment]
> Code looks good to me too. Conflicts just need to be resolved. One question though - since this is for Blade do we want to align these updates with our recent release (20.2), rather than putting them in the next release (21.0)?

Ok. I merged and committed. The changes here are for Blade, but also for anyone who uses Cura in Dark Mode. If you want to commit it to r20.2 that is fine. Also, we will need to create a branch and add in the BR materials database for the Beta

**Comment by bradymadams** [comment]
> Ok. I merged and committed. The changes here are for Blade, but also for anyone who uses Cura in Dark Mode. If you want to commit it to r20.2 that is fine. Also, we will need to create a branch and add in the BR materials database for the Beta

I'll hold on merging anything here. You and I should probably just have a quick chat this morning and create a game plan for this

**Comment by bradymadams** [comment]
See #472

**Pull request closed without merging**
